#!/bin/bash
telnet https://www.bing.com/ck/a?!&&p=5d7d29f850e46073JmltdHM9MTY3ODQwNjQwMCZpZ3VpZD0xYTJhMjM3Yy0xNjhlLTY1MjEtM2M5MC0zMWMyMTc5MzY0ZmQmaW5zaWQ9NTIyMw&ptn=3&hsh=3&fclid=1a2a237c-168e-6521-3c90-31c2179364fd&psq=starwars+iv+episode&u=a1aHR0cHM6Ly93d3cuc3RhcndhcnMuY29tL2ZpbG1zL3N0YXItd2Fycy1lcGlzb2RlLWl2LWEtbmV3LWhvcGU&ntb=1
